package ly.neptune.signal.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class SignalColors(
    val dark: Boolean = false,
    val black: Boolean = false,
    val primary: Color = Color(0xFF07315F),
    val onPrimary: Color = Color(0xFFFFFFFF),
    val primaryContainer: Color = Color(0xFFE8F1FF),
    val onPrimaryContainer: Color = Color(0xFF061D38),
    val secondary: Color = Color(0xFF006D72),
    val onSecondary: Color = Color(0xFFFFFFFF),
    val secondaryContainer: Color = Color(0xFFD8F6F7),
    val onSecondaryContainer: Color = Color(0xFF073A3D),
    val tertiary: Color = Color(0xFFEB4E4D),
    val onTertiary: Color = Color(0xFFFFFFFF),
    val tertiaryContainer: Color = Color(0xFFFFE5E4),
    val onTertiaryContainer: Color = Color(0xFF541312),
    val surface: Color = Color(0xFFFAFCFC),
    val surfaceDim: Color = Color(0xFFDCE6E8),
    val surfaceBright: Color = Color(0xFFFFFFFF),
    val surfaceContainerLowest: Color = Color(0xFFFFFFFF),
    val surfaceContainerLow: Color = Color(0xFFF4F8F8),
    val surfaceContainer: Color = Color(0xFFEEF5F5),
    val surfaceContainerHigh: Color = Color(0xFFE7F0F1),
    val surfaceContainerHighest: Color = Color(0xFFDDE8EA),
    val onSurface: Color = Color(0xFF071C2E),
    val onSurfaceVariant: Color = Color(0xFF60747C),
    val outline: Color = Color(0xFFC8D8DD),
    val outlineVariant: Color = Color(0xFFE0EAED),
    val inverseSurface: Color = Color(0xFF071C2E),
    val inverseOnSurface: Color = Color(0xFFFFFFFF),
    val error: Color = Color(0xFFC33131),
    val onError: Color = Color(0xFFFFFFFF),
    val errorContainer: Color = Color(0xFFFFE3E0),
    val onErrorContainer: Color = Color(0xFF5A1111),
    val success: Color = Color(0xFF0B8F67),
    val warning: Color = Color(0xFFA96A13),
    val danger: Color = error,
    val bankPrimary: Color = primary,
    val bankSecondary: Color = Color(0xFF00A8AE),
    val bankAccent: Color = tertiary,
    val surfacePaper: Color = surface,
    val surfaceCard: Color = surfaceContainerLowest,
    val surfaceSoft: Color = surfaceContainer,
    val textPrimary: Color = onSurface,
    val textSecondary: Color = onSurfaceVariant,
    val textInverse: Color = onPrimary,
    val borderDefault: Color = outlineVariant,
)

object SignalColorDefaults {
    val Neptune = SignalColors()
    val NeptuneDark = SignalColors(
        dark = true,
        primary = Color(0xFF6FB8FF),
        onPrimary = Color(0xFF041B32),
        primaryContainer = Color(0xFF17385E),
        onPrimaryContainer = Color(0xFFE5F1FF),
        secondary = Color(0xFF4FD5D9),
        onSecondary = Color(0xFF00363A),
        secondaryContainer = Color(0xFF0B464A),
        onSecondaryContainer = Color(0xFFD9FAFB),
        tertiary = Color(0xFFFFB3AE),
        onTertiary = Color(0xFF5F1513),
        tertiaryContainer = Color(0xFF7D2523),
        onTertiaryContainer = Color(0xFFFFE5E4),
        surface = Color(0xFF071217),
        surfaceDim = Color(0xFF050D12),
        surfaceBright = Color(0xFF1B2C34),
        surfaceContainerLowest = Color(0xFF09181E),
        surfaceContainerLow = Color(0xFF0E1E25),
        surfaceContainer = Color(0xFF142832),
        surfaceContainerHigh = Color(0xFF1A333D),
        surfaceContainerHighest = Color(0xFF254550),
        onSurface = Color(0xFFEEF7F8),
        onSurfaceVariant = Color(0xFF9DB1B8),
        outline = Color(0xFF38555F),
        outlineVariant = Color(0xFF263F48),
        inverseSurface = Color(0xFFEAF2F4),
        inverseOnSurface = Color(0xFF071217),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        success = Color(0xFF58D6A9),
        warning = Color(0xFFFFC56D),
        danger = Color(0xFFFFB4AB),
        bankPrimary = Color(0xFF07315F),
        bankSecondary = Color(0xFF00A8AE),
        bankAccent = Color(0xFFEB4E4D),
        surfacePaper = Color(0xFF071217),
        surfaceCard = Color(0xFF09181E),
        surfaceSoft = Color(0xFF142832),
        textPrimary = Color(0xFFEEF7F8),
        textSecondary = Color(0xFF9DB1B8),
        textInverse = Color(0xFF041B32),
        borderDefault = Color(0xFF263F48),
    )
    val NeptuneBlack = SignalColors(
        dark = true,
        black = true,
        primary = Color(0xFF6FB8FF),
        onPrimary = Color(0xFF041B32),
        primaryContainer = Color(0xFF102D4D),
        onPrimaryContainer = Color(0xFFE5F1FF),
        secondary = Color(0xFF4FD5D9),
        onSecondary = Color(0xFF00363A),
        secondaryContainer = Color(0xFF063D41),
        onSecondaryContainer = Color(0xFFD9FAFB),
        tertiary = Color(0xFFFFB3AE),
        onTertiary = Color(0xFF5F1513),
        tertiaryContainer = Color(0xFF67201E),
        onTertiaryContainer = Color(0xFFFFE5E4),
        surface = Color(0xFF000000),
        surfaceDim = Color(0xFF000000),
        surfaceBright = Color(0xFF111B20),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF05080A),
        surfaceContainer = Color(0xFF080F13),
        surfaceContainerHigh = Color(0xFF0D171C),
        surfaceContainerHighest = Color(0xFF14242B),
        onSurface = Color(0xFFF4FBFC),
        onSurfaceVariant = Color(0xFFAABBC1),
        outline = Color(0xFF2C454E),
        outlineVariant = Color(0xFF1B2C33),
        inverseSurface = Color(0xFFEAF2F4),
        inverseOnSurface = Color(0xFF000000),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        success = Color(0xFF58D6A9),
        warning = Color(0xFFFFC56D),
        danger = Color(0xFFFFB4AB),
        bankPrimary = Color(0xFF07315F),
        bankSecondary = Color(0xFF00A8AE),
        bankAccent = Color(0xFFEB4E4D),
        surfacePaper = Color(0xFF000000),
        surfaceCard = Color(0xFF05080A),
        surfaceSoft = Color(0xFF080F13),
        textPrimary = Color(0xFFF4FBFC),
        textSecondary = Color(0xFFAABBC1),
        textInverse = Color(0xFF041B32),
        borderDefault = Color(0xFF1B2C33),
    )

    fun whiteLabel(
        primary: Color,
        secondary: Color = Color(0xFF00A8AE),
        accent: Color = Color(0xFFEB4E4D),
        ink: Color = Color(0xFF071C2E),
        surface: Color = Color(0xFFFAFCFC),
        primaryContainer: Color = Color(0xFFE8F1FF),
        secondaryContainer: Color = Color(0xFFD8F6F7),
        tertiaryContainer: Color = Color(0xFFFFE5E4),
        dark: Boolean = false,
        black: Boolean = false,
    ): SignalColors = when {
        black -> whiteLabelBlack(primary = primary, secondary = secondary, accent = accent)
        dark -> whiteLabelDark(primary = primary, secondary = secondary, accent = accent)
        else -> SignalColors(
            primary = primary,
            onPrimary = contentColorFor(primary),
            primaryContainer = primaryContainer,
            onPrimaryContainer = ink,
            secondary = secondary,
            onSecondary = contentColorFor(secondary),
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = ink,
            tertiary = accent,
            onTertiary = contentColorFor(accent),
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = ink,
            surface = surface,
            onSurface = ink,
            bankPrimary = primary,
            bankSecondary = secondary,
            bankAccent = accent,
            surfacePaper = surface,
            textPrimary = ink,
            textInverse = contentColorFor(primary),
        )
    }

    fun whiteLabelDark(
        primary: Color,
        secondary: Color = Color(0xFF4FD5D9),
        accent: Color = Color(0xFFFFB3AE),
        surface: Color = Color(0xFF071217),
    ) = NeptuneDark.copy(
        primary = primary,
        onPrimary = contentColorFor(primary),
        primaryContainer = Color(0xFF17385E),
        onPrimaryContainer = Color.White,
        secondary = secondary,
        onSecondary = contentColorFor(secondary),
        tertiary = accent,
        onTertiary = contentColorFor(accent),
        surface = surface,
        bankPrimary = primary,
        bankSecondary = secondary,
        bankAccent = accent,
        surfacePaper = surface,
        surfaceCard = Color(0xFF09181E),
        surfaceSoft = Color(0xFF142832),
        textInverse = contentColorFor(primary),
    )

    fun whiteLabelBlack(
        primary: Color,
        secondary: Color = Color(0xFF4FD5D9),
        accent: Color = Color(0xFFFFB3AE),
        surface: Color = Color(0xFF000000),
    ) = NeptuneBlack.copy(
        primary = primary,
        onPrimary = contentColorFor(primary),
        primaryContainer = Color(0xFF102D4D),
        onPrimaryContainer = Color.White,
        secondary = secondary,
        onSecondary = contentColorFor(secondary),
        tertiary = accent,
        onTertiary = contentColorFor(accent),
        surface = surface,
        bankPrimary = primary,
        bankSecondary = secondary,
        bankAccent = accent,
        surfacePaper = surface,
        surfaceCard = Color(0xFF05080A),
        surfaceSoft = Color(0xFF080F13),
        textInverse = contentColorFor(primary),
    )

    private fun contentColorFor(color: Color): Color {
        val luma = (0.299f * color.red) + (0.587f * color.green) + (0.114f * color.blue)
        return if (luma > 0.62f) Color(0xFF071C2E) else Color.White
    }
}
