package ly.neptune.signal.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class SignalColors(
    val primary: Color = Color(0xFF07315F),
    val onPrimary: Color = Color(0xFFFFFFFF),
    val primaryContainer: Color = Color(0xFFE8F1FF),
    val onPrimaryContainer: Color = Color(0xFF061D38),
    val secondary: Color = Color(0xFF006D72),
    val onSecondary: Color = Color(0xFFFFFFFF),
    val secondaryContainer: Color = Color(0xFFD8F6F7),
    val onSecondaryContainer: Color = Color(0xFF073A3D),
    val tertiary: Color = Color(0xFFEB4E4D),
    val onTertiary: Color = Color(0xFFFFFFFF),
    val tertiaryContainer: Color = Color(0xFFFFE5E4),
    val onTertiaryContainer: Color = Color(0xFF541312),
    val surface: Color = Color(0xFFFAFCFC),
    val surfaceDim: Color = Color(0xFFDCE6E8),
    val surfaceBright: Color = Color(0xFFFFFFFF),
    val surfaceContainerLowest: Color = Color(0xFFFFFFFF),
    val surfaceContainerLow: Color = Color(0xFFF4F8F8),
    val surfaceContainer: Color = Color(0xFFEEF5F5),
    val surfaceContainerHigh: Color = Color(0xFFE7F0F1),
    val surfaceContainerHighest: Color = Color(0xFFDDE8EA),
    val onSurface: Color = Color(0xFF071C2E),
    val onSurfaceVariant: Color = Color(0xFF60747C),
    val outline: Color = Color(0xFFC8D8DD),
    val outlineVariant: Color = Color(0xFFE0EAED),
    val inverseSurface: Color = Color(0xFF071C2E),
    val inverseOnSurface: Color = Color(0xFFFFFFFF),
    val error: Color = Color(0xFFC33131),
    val onError: Color = Color(0xFFFFFFFF),
    val errorContainer: Color = Color(0xFFFFE3E0),
    val onErrorContainer: Color = Color(0xFF5A1111),
    val success: Color = Color(0xFF0B8F67),
    val warning: Color = Color(0xFFA96A13),
    val danger: Color = error,
    val bankPrimary: Color = primary,
    val bankSecondary: Color = Color(0xFF00A8AE),
    val bankAccent: Color = tertiary,
    val surfacePaper: Color = surface,
    val surfaceCard: Color = surfaceContainerLowest,
    val surfaceSoft: Color = surfaceContainer,
    val textPrimary: Color = onSurface,
    val textSecondary: Color = onSurfaceVariant,
    val textInverse: Color = onPrimary,
    val borderDefault: Color = outlineVariant,
)

object SignalColorDefaults {
    val Neptune = SignalColors()

    fun whiteLabel(
        primary: Color,
        secondary: Color = Color(0xFF00A8AE),
        accent: Color = Color(0xFFEB4E4D),
        ink: Color = Color(0xFF071C2E),
        surface: Color = Color(0xFFFAFCFC),
        primaryContainer: Color = Color(0xFFE8F1FF),
        secondaryContainer: Color = Color(0xFFD8F6F7),
        tertiaryContainer: Color = Color(0xFFFFE5E4),
    ) = SignalColors(
        primary = primary,
        onPrimary = Color.White,
        primaryContainer = primaryContainer,
        onPrimaryContainer = ink,
        secondary = secondary,
        onSecondary = Color.White,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = ink,
        tertiary = accent,
        onTertiary = Color.White,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = ink,
        surface = surface,
        onSurface = ink,
        bankPrimary = primary,
        bankSecondary = secondary,
        bankAccent = accent,
        surfacePaper = surface,
        textPrimary = ink,
    )
}
